name: build
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - README.md
      - .github/workflows/release.yml

env:
  BUILD_VERSION: "0.15.3"
  GIT_REPO: https://github.com/januson/docker-image-zola
  REPOSITORY: januson/zola

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@1
        with:
          egress-policy: audit

      - name: Source checkout
        uses: actions/checkout@v3
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REPOSITORY }}
          labels: |
            org.opencontainers.image.vendor="januson"
            org.opencontainers.image.licenses="MIT"
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ env.GIT_REPO }}
            org.opencontainers.image.title=${{ env.REPOSITORY }}
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}

      - name: Build and push zola
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            ${{ env.REPOSITORY }}:latest
          build-args: |
            ZOLA_VERSION=${{ env.BUILD_VERSION }}

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ env.REPOSITORY }}
