name: build
on:
  push:
    branches:
      - master
    paths:
      - Dockerfile
      - .github/workflows/release.yml
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * 1"

env:
  BUILD_VERSION: "0.16.0"
  GIT_REPO: https://github.com/januson/docker-image-zola
  REPOSITORY: januson/zola

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@74b568e8591fbb3115c70f3436a0c6b0909a8504 # v1
        with:
          egress-policy: audit
          disable-telemetry: true
          allowed-endpoints: >
            api.github.com:443
            auth.docker.io:443
            codeload.github.com:443
            crates.io:443
            dl-cdn.alpinelinux.org:443
            github.com:443
            production.cloudflare.docker.com:443
            registry-1.docker.io:443
            static.crates.io:443

      - name: Source checkout
        uses: actions/checkout@v3
      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set Docker metadata
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REPOSITORY }}
          labels: |
            org.opencontainers.image.vendor="januson"
            org.opencontainers.image.licenses="MIT"
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.source=${{ env.GIT_REPO }}
            org.opencontainers.image.title=${{ env.REPOSITORY }}
            org.opencontainers.image.version=${{ env.BUILD_VERSION }}

      - name: Build and push zola
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ env.REPOSITORY }}:${{ env.BUILD_VERSION }}
            ${{ env.REPOSITORY }}:latest
          build-args: |
            ZOLA_VERSION=${{ env.BUILD_VERSION }}
